"""
config/app_registry.py
──────────────────────
Static dictionaries that map voice-spoken names to OS commands or
known process names.  Keep this purely declarative – no logic here.
"""

SPECIAL_APPS: dict[str, str] = {
    "word":                 "start winword",
    "microsoft word":       "start winword",
    "excel":                "start excel",
    "microsoft excel":      "start excel",
    "powerpoint":           "start powerpnt",
    "microsoft powerpoint": "start powerpnt",
    "outlook":              "start outlook",
    "microsoft outlook":    "start outlook",
    "onenote":              "start onenote",
    "microsoft onenote":    "start onenote",
    "access":               "start msaccess",
    "settings":             "start ms-settings:",
    "windows settings":     "start ms-settings:",
    "control panel":        "start control",
    "task manager":         "start taskmgr",
    "file explorer":        "start explorer",
    "explorer":             "start explorer",
    "paint":                "start mspaint",
    "notepad":              "start notepad",
    "calculator":           "start calc",
    "cmd":                  "start cmd",
    "command prompt":       "start cmd",
    "powershell":           "start powershell",
    "snipping tool":        "start snippingtool",
    "chrome":               "start chrome",
    "google chrome":        "start chrome",
    "edge":                 "start msedge",
    "microsoft edge":       "start msedge",
    "firefox":              "start firefox",
    "camera":               "start microsoft.windows.camera:",
    "mail":                 "start outlookmail:",
    "calendar":             "start outlookcal:",
    "maps":                 "start bingmaps:",
    "store":                "start ms-windows-store:",
    "microsoft store":      "start ms-windows-store:",
    "xbox":                 "start xbox:",
    "photos":               "start ms-photos:",
    "clock":                "start ms-clock:",
    "weather":              "start bingweather:",
    "sticky notes":         "start ms-stickynotes:",
    "teams":                "start msteams:",
    "youtube":              "start https://www.youtube.com",
    "google":               "start https://www.google.com",
    "whatsapp web":         "start https://web.whatsapp.com",
}

PROCESS_ALIASES: dict[str, str] = {
    "vs code":           "code.exe",
    "vscode":            "code.exe",
    "visual studio code":"code.exe",
    "visual studio":     "devenv.exe",
    "word":              "winword.exe",
    "excel":             "excel.exe",
    "powerpoint":        "powerpnt.exe",
    "outlook":           "outlook.exe",
    "teams":             "teams.exe",
    "chrome":            "chrome.exe",
    "firefox":           "firefox.exe",
    "edge":              "msedge.exe",
    "spotify":           "spotify.exe",
    "discord":           "discord.exe",
    "steam":             "steam.exe",
    "notepad":           "notepad.exe",
    "paint":             "mspaint.exe",
    "calculator":        "calculatorapp.exe",
    "task manager":      "taskmgr.exe",
    "file explorer":     "explorer.exe",
    "vlc":               "vlc.exe",
    "zoom":              "zoom.exe",
    "obs":               "obs64.exe",
    "telegram":          "telegram.exe",
    "whatsapp":          "whatsapp.exe",
    "postman":           "postman.exe",
    "pycharm":           "pycharm64.exe",
    "android studio":    "studio64.exe",
    "blender":           "blender.exe",
    "photoshop":         "photoshop.exe",
    "premiere":          "premiere.exe",
    "after effects":     "afterfx.exe",
    "figma":             "figma.exe",
    "notion":            "notion.exe",
    "slack":             "slack.exe",
}